/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5;

import java.awt.Color;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo Banegas
 */
public class Clash extends javax.swing.JFrame {

    /**
     * Creates new form Clash
     */
    public Clash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevo_jugador = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jb_color = new javax.swing.JButton();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        pf_contrasena = new javax.swing.JPasswordField();
        tf_user = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        nuevo_mazo = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cb_carta3 = new javax.swing.JComboBox<>();
        cb_carta2 = new javax.swing.JComboBox<>();
        cb_mazo3 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        tf_nombre_mazo = new javax.swing.JTextField();
        asignar_mazos = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cb_mazo1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cb_mazo2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cb_mazo31 = new javax.swing.JComboBox<>();
        agregar_mazos_jugadores = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cb_jugadores = new javax.swing.JComboBox<>();
        login_jugador = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jt_username = new javax.swing.JTextField();
        pf_pass = new javax.swing.JPasswordField();
        jb_ingresar = new javax.swing.JButton();
        nueva_carta = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_nueva_carta = new javax.swing.JTextField();
        cb_nueva_carta = new javax.swing.JComboBox<>();
        jb_crear_carta = new javax.swing.JButton();
        js_dano = new javax.swing.JSpinner();
        barra_jugador = new javax.swing.JMenuBar();
        menu_jugador = new javax.swing.JMenu();
        mi_login_jugador = new javax.swing.JMenuItem();
        mi_nuevo_jugador = new javax.swing.JMenuItem();
        asignar_mazo = new javax.swing.JMenuItem();
        mi_logout = new javax.swing.JMenuItem();
        menu_clan = new javax.swing.JMenu();
        mi_unirse_clan = new javax.swing.JMenuItem();
        mi_nuevo_clan = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_nueva_carta = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nuevo jugador");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Nombre de usuario:");

        jLabel5.setText("Contraseña:");

        jLabel6.setText("Fecha de nacimiento:");

        jLabel7.setText("Color favorito:");

        jb_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_colorActionPerformed(evt);
            }
        });

        jButton2.setText("Crear jugador");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nuevo_jugadorLayout = new javax.swing.GroupLayout(nuevo_jugador.getContentPane());
        nuevo_jugador.getContentPane().setLayout(nuevo_jugadorLayout);
        nuevo_jugadorLayout.setHorizontalGroup(
            nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevo_jugadorLayout.createSequentialGroup()
                .addGroup(nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevo_jugadorLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1))
                    .addGroup(nuevo_jugadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_color, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(tf_user)
                            .addComponent(tf_apellido)
                            .addComponent(tf_nombre))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevo_jugadorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(249, 249, 249))
        );
        nuevo_jugadorLayout.setVerticalGroup(
            nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevo_jugadorLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevo_jugadorLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)
                        .addGroup(nuevo_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_color, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(nuevo_jugadorLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7))))
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(74, 74, 74))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Nuevo mazo");

        jLabel10.setText("Carta 1:");

        jLabel11.setText("Carta 2:");

        jLabel12.setText("Carta 3:");

        jButton1.setText("Crear mazo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Nombre del mazo: ");

        javax.swing.GroupLayout nuevo_mazoLayout = new javax.swing.GroupLayout(nuevo_mazo.getContentPane());
        nuevo_mazo.getContentPane().setLayout(nuevo_mazoLayout);
        nuevo_mazoLayout.setHorizontalGroup(
            nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevo_mazoLayout.createSequentialGroup()
                .addGroup(nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(nuevo_mazoLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel9)))
                    .addGroup(nuevo_mazoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(36, 36, 36)
                        .addGroup(nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_carta3, 0, 365, Short.MAX_VALUE)
                            .addComponent(cb_mazo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_carta2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(nuevo_mazoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nombre_mazo, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        nuevo_mazoLayout.setVerticalGroup(
            nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevo_mazoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addGap(49, 49, 49)
                .addGroup(nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(42, 42, 42)
                .addGroup(nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mazo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(41, 41, 41)
                .addGroup(nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(36, 36, 36)
                .addGroup(nuevo_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_nombre_mazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Asignar mazos");

        jLabel13.setText("Mazo 1:");

        cb_mazo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel14.setText("Mazo 2: ");

        jLabel15.setText("Mazo 3: ");

        agregar_mazos_jugadores.setText("Asignar");
        agregar_mazos_jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_mazos_jugadoresActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Usuario:");

        javax.swing.GroupLayout asignar_mazosLayout = new javax.swing.GroupLayout(asignar_mazos.getContentPane());
        asignar_mazos.getContentPane().setLayout(asignar_mazosLayout);
        asignar_mazosLayout.setHorizontalGroup(
            asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignar_mazosLayout.createSequentialGroup()
                .addGroup(asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(asignar_mazosLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(agregar_mazos_jugadores))
                    .addGroup(asignar_mazosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(asignar_mazosLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_mazo1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(asignar_mazosLayout.createSequentialGroup()
                                .addGroup(asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(4, 4, 4)
                                .addGroup(asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_mazo31, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_mazo2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(asignar_mazosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(cb_jugadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignar_mazosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(129, 129, 129))
        );
        asignar_mazosLayout.setVerticalGroup(
            asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignar_mazosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cb_jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cb_mazo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mazo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(52, 52, 52)
                .addGroup(asignar_mazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mazo31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(62, 62, 62)
                .addComponent(agregar_mazos_jugadores)
                .addGap(28, 28, 28))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Log In Jugador");

        jLabel18.setText("Nombre de usuario:");

        jLabel19.setText("Contraseña:");

        jb_ingresar.setText("Ingresar");
        jb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout login_jugadorLayout = new javax.swing.GroupLayout(login_jugador.getContentPane());
        login_jugador.getContentPane().setLayout(login_jugadorLayout);
        login_jugadorLayout.setHorizontalGroup(
            login_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_jugadorLayout.createSequentialGroup()
                .addGroup(login_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_jugadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(login_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(24, 24, 24)
                        .addGroup(login_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addComponent(jt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(pf_pass, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(login_jugadorLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jb_ingresar)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        login_jugadorLayout.setVerticalGroup(
            login_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_jugadorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel17)
                .addGap(69, 69, 69)
                .addGroup(login_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(login_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jb_ingresar)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("Nueva Carta");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Nombre:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Daño:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Tipo:");

        cb_nueva_carta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Montapuercos", "Minipekka", "Golem", "Leñador", "Dragon", "Dragon Infernal", "Gigante Noble", "Pandilla de duendes" }));

        jb_crear_carta.setText("Crear nueva carta");
        jb_crear_carta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crear_cartaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nueva_cartaLayout = new javax.swing.GroupLayout(nueva_carta.getContentPane());
        nueva_carta.getContentPane().setLayout(nueva_cartaLayout);
        nueva_cartaLayout.setHorizontalGroup(
            nueva_cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nueva_cartaLayout.createSequentialGroup()
                .addGroup(nueva_cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nueva_cartaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(nueva_cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(nueva_cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nueva_carta)
                            .addComponent(cb_nueva_carta, 0, 233, Short.MAX_VALUE)
                            .addComponent(js_dano, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(nueva_cartaLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jb_crear_carta))
                    .addGroup(nueva_cartaLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel20)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        nueva_cartaLayout.setVerticalGroup(
            nueva_cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nueva_cartaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel20)
                .addGap(54, 54, 54)
                .addGroup(nueva_cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_nueva_carta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(nueva_cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(js_dano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(nueva_cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cb_nueva_carta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(jb_crear_carta)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_jugador.setText("Jugador");

        mi_login_jugador.setText("Log in");
        mi_login_jugador.setEnabled(false);
        mi_login_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_login_jugadorActionPerformed(evt);
            }
        });
        menu_jugador.add(mi_login_jugador);

        mi_nuevo_jugador.setText("Nuevo jugador");
        mi_nuevo_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_nuevo_jugadorActionPerformed(evt);
            }
        });
        menu_jugador.add(mi_nuevo_jugador);

        asignar_mazo.setText("Asignar mazos a jugador");
        asignar_mazo.setEnabled(false);
        asignar_mazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignar_mazoActionPerformed(evt);
            }
        });
        menu_jugador.add(asignar_mazo);

        mi_logout.setText("Log out");
        mi_logout.setEnabled(false);
        mi_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_logoutActionPerformed(evt);
            }
        });
        menu_jugador.add(mi_logout);

        barra_jugador.add(menu_jugador);

        menu_clan.setText("Clan");

        mi_unirse_clan.setText("Unirse a un clan");
        mi_unirse_clan.setEnabled(false);
        menu_clan.add(mi_unirse_clan);

        mi_nuevo_clan.setText("Crear un clan");
        menu_clan.add(mi_nuevo_clan);

        barra_jugador.add(menu_clan);

        jMenu1.setText("Mazos");

        jMenuItem1.setText("Crear Mazo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        barra_jugador.add(jMenu1);

        jMenu2.setText("Cartas");

        mi_nueva_carta.setText("Nueva carta");
        mi_nueva_carta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_nueva_cartaActionPerformed(evt);
            }
        });
        jMenu2.add(mi_nueva_carta);

        barra_jugador.add(jMenu2);

        setJMenuBar(barra_jugador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 976, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asignar_mazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignar_mazoActionPerformed
        // TODO add your handling code here:
        asignar_mazos.setModal(true);
        asignar_mazos.pack();
        asignar_mazos.setLocationRelativeTo(this);
        asignar_mazos.setVisible(true);
    }//GEN-LAST:event_asignar_mazoActionPerformed

    private void mi_nuevo_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_nuevo_jugadorActionPerformed
        // TODO add your handling code here:
    nuevo_jugador.setModal(true);
    nuevo_jugador.pack();
    nuevo_jugador.setLocationRelativeTo(this);
    nuevo_jugador.setVisible(true);
    }//GEN-LAST:event_mi_nuevo_jugadorActionPerformed

    private void jb_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_colorActionPerformed
        Color c;
        c=JColorChooser.showDialog(this, "Seleccione un color", Color.yellow);
        jb_color.setBackground(c);
    }//GEN-LAST:event_jb_colorActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    String nombre;
    String apellido;
    String user;
    String contrasena;
    Date fecha;
    int edad;
    Color color;
    nombre=tf_nombre.getText();
    apellido=tf_apellido.getText();
    user=tf_user.getText();
    contrasena=pf_contrasena.getText();
    fecha=dc_fecha.getDate();
    edad=(int)(((new Date()).getTime()-fecha.getTime())/(1000*60*60*24)/365);
    color=jb_color.getBackground();
    DefaultComboBoxModel modelo=(DefaultComboBoxModel)cb_jugadores.getModel();
    modelo.addElement(new Usuarios(nombre,apellido,user,contrasena,fecha,edad,color));
    cb_jugadores.setModel(modelo);
    JOptionPane.showMessageDialog(this, "Jugador creado exitosamente");
    tf_nombre.setText("");
    tf_apellido.setText("");
    tf_user.setText("");
    pf_contrasena.setText("");
    jb_color.setBackground(Color.blue);
    dc_fecha.setDate(new Date());
    nuevo_jugador.setVisible(false);
    mi_login_jugador.setEnabled(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo= (DefaultComboBoxModel)cb_jugadores.getModel();
        String user, password;
        Boolean t=false;
        for (int i = 0; i < modelo.getSize(); i++) {
            user=((Usuarios)modelo.getElementAt(i)).getUser();
            password=((Usuarios)modelo.getElementAt(i)).getContraseña();
            if (user.equals(jt_username.getText()) && password.equals(pf_pass.getText()))
            {
                t=true;
                JOptionPane.showMessageDialog(this, "Bienvenido");
                asignar_mazo.setEnabled(true);
                mi_logout.setEnabled(true);
                usuario=(Usuarios)modelo.getElementAt(i);
                login_jugador.setVisible(false); 
            }
            
        }
        if (t==false)
        {
            JOptionPane.showMessageDialog(this, "Nombre de usuario y/o contrase;a incorrecto");
            pf_pass.setText("");
            jt_username.setText("");
        }
    }//GEN-LAST:event_jb_ingresarMouseClicked

    private void mi_login_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_login_jugadorActionPerformed
        // TODO add your handling code here:
        login_jugador.setModal(true);
        login_jugador.pack();
        login_jugador.setLocationRelativeTo(this);
        login_jugador.setVisible(true);
    }//GEN-LAST:event_mi_login_jugadorActionPerformed

    private void mi_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_logoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Bye Bye");
        DefaultComboBoxModel modelo=(DefaultComboBoxModel)cb_jugadores.getModel();
        if (modelo.getSize()>-1)
        {
            mi_login_jugador.setEnabled(true);
            mi_logout.setEnabled(false);
            mi_nuevo_jugador.setEnabled(true);
        }
        else
        {
            mi_login_jugador.setEnabled(false);
            mi_logout.setEnabled(false);
            mi_nuevo_jugador.setEnabled(true);
        }
    }//GEN-LAST:event_mi_logoutActionPerformed

    private void jb_crear_cartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crear_cartaActionPerformed
        // TODO add your handling code here:
        String nombre;
        DefaultComboBoxModel modelo=(DefaultComboBoxModel)cb_carta3.getModel();
        int dano;
        nombre=tf_nueva_carta.getText();
        dano=(int)js_dano.getValue();
        String tipo=(String)cb_nueva_carta.getSelectedItem();
        if (tipo.equals("Minipekka"))
        {
            Minipekka s=new Minipekka();
            s.setNombre(nombre);
            s.setDaño(dano);
            modelo.addElement(s);
            cb_carta3.setModel(modelo);
            cb_carta2.setModel(modelo);
            cb_mazo3.setModel(modelo);
        }
        if (tipo.equals("Montapuerco"))
        {
            Montapuerco s=new Montapuerco();
            s.setNombre(nombre);
            s.setDaño(dano);
            modelo.addElement(s);
            cb_carta3.setModel(modelo);
            cb_carta2.setModel(modelo);
            cb_mazo3.setModel(modelo);
        }if (tipo.equals("Golem"))
        {
            Golem s=new Golem();
            s.setNombre(nombre);
            s.setDaño(dano);
            modelo.addElement(s);
            cb_carta3.setModel(modelo);
            cb_carta2.setModel(modelo);
            cb_mazo3.setModel(modelo);
        }
        if (tipo.equals("Lenador"))
        {
            Lenador s=new Lenador();
            s.setNombre(nombre);
            s.setDaño(dano);
            modelo.addElement(s);
            cb_carta3.setModel(modelo);
            cb_carta2.setModel(modelo);
            cb_mazo3.setModel(modelo);
        }
        if (tipo.equals("Dragon Infernal"))
        {
            DragonI s=new DragonI();
            s.setNombre(nombre);
            s.setDaño(dano);
            modelo.addElement(s);
            cb_carta3.setModel(modelo);
            cb_carta2.setModel(modelo);
            cb_mazo3.setModel(modelo);
        }
        if (tipo.equals("Dragon"))
        {
            Dragon s=new Dragon();
            s.setNombre(nombre);
            s.setDaño(dano);
            modelo.addElement(s);
            cb_carta3.setModel(modelo);
            cb_carta2.setModel(modelo);
            cb_mazo3.setModel(modelo);
        }
        if (tipo.equals("Gigante Noble"))
        {
           Gigante s=new Gigante();
            s.setNombre(nombre);
            s.setDaño(dano);
            modelo.addElement(s);
            cb_carta3.setModel(modelo);
            cb_carta2.setModel(modelo);
            cb_mazo3.setModel(modelo);
        }
        if (tipo.equals("Pandilla de duendes"))
        {
            Pandilla s=new Pandilla();
            s.setNombre(nombre);
            s.setDaño(dano);
            modelo.addElement(s);
            cb_carta3.setModel(modelo);
            cb_carta2.setModel(modelo);
            cb_mazo3.setModel(modelo);
        }
        nueva_carta.setVisible(false);
    }//GEN-LAST:event_jb_crear_cartaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo=(DefaultComboBoxModel)cb_mazo1.getModel();
        String nombre=tf_nombre_mazo.getText();
        int c1=((Cartas)cb_carta3.getSelectedItem()).getCoste();
        int c2=((Cartas)cb_carta2.getSelectedItem()).getCoste();
        int c3=((Cartas)cb_carta3.getSelectedItem()).getCoste();
        int coste=(c1+c2+c3)/3;
        Mazos mazo=new Mazos(nombre,coste,(Cartas)cb_carta3.getSelectedItem(),  (Cartas)cb_carta2.getSelectedItem(), (Cartas)cb_mazo3.getSelectedItem());
        modelo.addElement(mazo);
        cb_mazo1.setModel(modelo);
        cb_mazo2.setModel(modelo);
        cb_mazo3.setModel(modelo);
        JOptionPane.showMessageDialog(this, "Mazo creado exitosamente");
        nuevo_mazo.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        nuevo_mazo.setModal(true);
        nuevo_mazo.pack();
        nuevo_mazo.setLocationRelativeTo(this);
        nuevo_mazo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mi_nueva_cartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_nueva_cartaActionPerformed
        // TODO add your handling code here:
        nueva_carta.setModal(true);
        nueva_carta.pack();
        nueva_carta.setLocationRelativeTo(this);
        nueva_carta.setVisible(true);
    }//GEN-LAST:event_mi_nueva_cartaActionPerformed

    private void agregar_mazos_jugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_mazos_jugadoresActionPerformed
        // TODO add your handling code here:
        Usuarios usuario;
        Mazos mazo1;
        Mazos mazo2;
        Mazos mazo3;
        usuario=(Usuarios)cb_jugadores.getSelectedItem();
        mazo1=(Mazos)cb_mazo1.getSelectedItem();
        mazo2=(Mazos)cb_mazo2.getSelectedItem();
        mazo3=(Mazos)cb_mazo3.getSelectedItem();
       usuario.getMazos().add(mazo1);
       usuario.getMazos().add(mazo2);
       usuario.getMazos().add(mazo3);
       JOptionPane.showMessageDialog(this, "Mazos agregados exitosamente");
       asignar_mazos.setVisible(false);
    }//GEN-LAST:event_agregar_mazos_jugadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_mazos_jugadores;
    private javax.swing.JMenuItem asignar_mazo;
    private javax.swing.JDialog asignar_mazos;
    private javax.swing.JMenuBar barra_jugador;
    private javax.swing.JComboBox<String> cb_carta2;
    private javax.swing.JComboBox<String> cb_carta3;
    private javax.swing.JComboBox<String> cb_jugadores;
    private javax.swing.JComboBox<String> cb_mazo1;
    private javax.swing.JComboBox<String> cb_mazo2;
    private javax.swing.JComboBox<String> cb_mazo3;
    private javax.swing.JComboBox<String> cb_mazo31;
    private javax.swing.JComboBox<String> cb_nueva_carta;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jb_color;
    private javax.swing.JButton jb_crear_carta;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JSpinner js_dano;
    private javax.swing.JTextField jt_username;
    private javax.swing.JDialog login_jugador;
    private javax.swing.JMenu menu_clan;
    private javax.swing.JMenu menu_jugador;
    private javax.swing.JMenuItem mi_login_jugador;
    private javax.swing.JMenuItem mi_logout;
    private javax.swing.JMenuItem mi_nueva_carta;
    private javax.swing.JMenuItem mi_nuevo_clan;
    private javax.swing.JMenuItem mi_nuevo_jugador;
    private javax.swing.JMenuItem mi_unirse_clan;
    private javax.swing.JDialog nueva_carta;
    private javax.swing.JDialog nuevo_jugador;
    private javax.swing.JDialog nuevo_mazo;
    private javax.swing.JPasswordField pf_contrasena;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre_mazo;
    private javax.swing.JTextField tf_nueva_carta;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
Usuarios usuario;





}